version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: monthly
    time: "00:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: core-js
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: core-js
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.3
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.2
  - dependency-name: rxjs
    versions:
    - 6.6.6
